app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('upload.urls', namespace='upload')),
]

upload/urls.py
from django.urls import path

from upload.views import UploadView

app_name = "upload"

#прописываем основной url нашего веб приложения 
urlpatterns = [path("", UploadView.as_view(), name="upload_page")]

upload/forms.py
import os
import ipaddress
from django import forms

from django.core.validators import validate_ipv4_address
from django.core.exceptions import ValidationError

#создаём форму для загрузки данных и валидируем эти данные
class UploadForm(forms.Form):
    ip_address = forms.CharField(
        label="ip",
        max_length=15,
        help_text="Введите IP адрес устройства: ",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    file = forms.FileField(
        label="file",
        help_text="Выберите файл прошивки размером до 10МБ",
        widget=forms.FileInput(attrs={"class": "form-control"}),
    )

#обрабатываем ошибки строки с IP адресом
    def clean_ip_address(self):
        ip_address = self.cleaned_data["ip_address"].strip()
        try:
            validate_ipv4_address(ip_address)
            ip = ipaddress.IPv4Address(ip_address)
            if ip.is_loopback or ip.is_multicast or ip.is_unspecified:
                raise ValidationError("IP-адрес введён неверно")
            return ip_address
        except ValidationError:
            raise ValidationError("Введите корректный IP-адрес")

#обрабатываем ошибки загружаемого файла
    def clean_file(self):
        file = self.cleaned_data["file"]
        max_size = 10 * 1024 * 1024
        if file.size > max_size:
            raise ValidationError("Файл слишком большой. Максимальный размер 10 МБ.")
        file_type = [".txt"]
        ext = os.path.splitext(file.name)[1].lower()
        if ext not in file_type:
            raise ValidationError(
                "Данный тип файла не поддерживается. Загрузите .txt файл."
            )
        return file

upload/views.py
import os
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import FormView

from upload.forms import UploadForm
from upload.utils import download_to_ftp

from dotenv import load_dotenv

load_dotenv()

#пишем представление для обработки формы и использования, отображения валидированных данных    
class UploadView(FormView):
    template_name = "upload/index.html"
    form_class = UploadForm
    success_url = reverse_lazy("upload:upload_page")

#получаем данные из templates
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

#валидируем эти данные и используем функцию для ftp из utils.py
#попутно отображаем успешность операции или ошибки с расшифровкой
    def form_valid(self, form):
        ip_address = form.cleaned_data["ip_address"]
        file = form.cleaned_data["file"]
        username = os.getenv('USER')
        password = os.getenv('USER_PASSWORD')

        try:
            success, report = download_to_ftp(ip_address, username, password, file)
            if success:
                messages.success(
                    self.request,
                    f"✅ Успешно! Файл {file.name} загружен на {ip_address}\n"
                    f"Отчёт сервера: {report}",
                )
            else:
                messages.warning(
                    self.request,
                    f"⚠️ Загрузка завершена с предупреждениями\n"
                    f"Отчёт сервера: {report}",
                )
        except Exception as e:
            messages.error(
                self.request,
                f"❌ Ошибка! Не удалось загрузить файл\n"
                f"Техническая информация: {str(e)}",
            )

        return super().form_valid(form)

templates/base.html
<!doctype html>
<html lang="ru">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>

    {% block content %}
    
    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

upload/templates/upload/index.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>
    </br>
    <h3>Введите IP-адрес и загрузите файл прошивки.</h3>
    </br>
        {% if messages %}
            {% for message in messages %}
                <div class="{% if message.tags == 'success' %}success{% else %}failure{% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </br>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="form-group">
                <label for="id_ip_address">Введите IP-адрес устройства:</label>
                <input type="text" name="ip_address" id="id_ip_address">
                {% if form.ip_address.errors %}
                    <div class="error">{{ form.ip_address.errors.0 }}</div>
                {% endif %}
            </div>
    </br>       
            <div class="form-group">
                <label for="id_file">Загрузите файл прошивки (.txt):</label>
                <input type="file" name="file" id="id_file" required>
                {% if form.file.errors %}
                    <div class="error">{{ form.file.errors.0 }}</div>
                {% endif %}
            </div>
    </br>       
            <button type="submit">Загрузить</button>
        </form>
</div>
{% endblock %}